import type { Metadata } from "next";
import Link from "next/link";
export const metadata:Metadata={title:"Services & pricing",description:"Compare New England Creatives Starter, Growth, and Partner monthly social media management packages.",alternates:{canonical:"/services"}};
const packages=[
 {id:"starter",name:"Starter",monthly:"$400",activation:"$150",items:["12 core content pieces per month","2 social platforms","Captions and branded graphics","Content calendar and scheduling","Local keyword and hashtag research","Optimization of client-supplied photos","Up to 2 short-form video edits from client footage","1 reasonable revision round per monthly batch","Basic monthly performance report"]},
 {id:"growth",name:"Growth",monthly:"$650",activation:"$200",items:["16 core content pieces per month","Up to 3 social platforms","All Starter planning, captions, graphics, scheduling, and research","Up to 4 short-form edits from client footage","Campaign and promotional content within the monthly count","Review-response assistance with agreed guidance","Detailed analytics and monthly strategy review","1 reasonable revision round per monthly batch"]},
 {id:"partner",name:"Partner",monthly:"$1,000",activation:"$300",items:["20 core content pieces per month","Up to 4 social platforms","All Growth planning, creative, scheduling, and optimization","Up to 6 short-form edits from client footage","More campaign and promotional content within the monthly count","Priority turnaround and closer strategy involvement","Detailed reporting and monthly strategy review","2 reasonable revision rounds per monthly batch"]},
];
export default function Services(){return <><div className="wrap page-hero"><p className="eyebrow">SERVICES & PRICING</p><h1>A marketing partner<br/><em>at your pace.</em></h1><p>Every package includes human-led strategy, a planned content cycle, and scheduling. We clarify the platforms, dates, and deliverables in your agreement before work begins.</p></div><div className="wrap package-list">{packages.map(p=><article className="package" id={p.id} key={p.id}><div><p className="eyebrow">{p.name.toUpperCase()}</p><h2>{p.monthly}<small style={{font:"500 1rem Montserrat"}}>/month</small></h2><p>{p.activation} one-time activation</p><Link className="button" href={"/get-started?package="+p.id}>Ask about {p.name} ↗</Link></div><div><ul>{p.items.map(x=><li key={x}>{x}</li>)}</ul></div></article>)}<p>“Core content piece” means one distinct post or video concept and its primary creative/caption. Platform adaptations of that same piece do not multiply the count. Client supplies business facts and usable source media. Paid advertising spend and management, on-site filming or photography, website/SEO work, daily community management, and unlimited revisions are outside these base packages unless separately agreed.</p></div></>}
