"use client";
import {useSearchParams} from "next/navigation";
import {useEffect,useState} from "react";
const questions:[string,string,string,boolean][]=[
 ["company","Business name","text",true],["contact","Primary contact","text",true],["email","Email","email",true],["serviceArea","Service area","text",false],["services","Services and priorities","textarea",true],["audience","Ideal customers","textarea",false],["differentiators","What makes you different?","textarea",false],["goals","Marketing goals","textarea",false],["socialUrls","Social profile URLs","textarea",false],["accessStatus","Platform role access status","text",false],["brand","Brand voice, colors, logo link","textarea",false],["assets","Approved photos, videos, and asset folder links","textarea",false],["restrictions","Topics, claims, imagery, or offers to avoid","textarea",false],["approver","Who approves content and how quickly?","text",false],["reporting","Reporting expectations","text",false]];
export default function OnboardingForm(){const token=useSearchParams().get("token")||"";const [state,setState]=useState("Checking link…"),[company,setCompany]=useState(""),[done,setDone]=useState(false);
 useEffect(()=>{if(!token){setState("Missing onboarding link.");return}fetch("/api/onboarding?token="+encodeURIComponent(token),{cache:"no-store"}).then(async r=>{const j=await r.json() as {error?:string,company?:string};if(!r.ok)throw Error(j.error);setCompany(j.company||"");setState("")}).catch(e=>setState(String(e)))},[token]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setState("Saving…");const p={...Object.fromEntries(new FormData(form).entries()),token};try{const r=await fetch("/api/onboarding",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(p)});const j=await r.json() as {error?:string};if(!r.ok)throw Error(j.error);setDone(true);setState("Your onboarding information has been saved. We’ll review it and contact you about any missing access or assets.")}catch(err){setState(String(err))}}
 return <form className="form-panel" onSubmit={submit}><h2 style={{fontSize:"2.5rem"}}>{company||"Your onboarding"}</h2>{state&&<p role="status">{state}</p>}{!state&&!done&&<><div className="form-grid">{questions.map(([name,label,type,required])=><div className={"field "+(type==="textarea"?"full":"")} key={name}><label htmlFor={name}>{label}{required?" *":""}</label>{type==="textarea"?<textarea id={name} name={name} required={required}/>:<input id={name} name={name} type={type} required={required} defaultValue={name==="company"?company:undefined}/>}</div>)}<div className="field full"><label htmlFor="portfolio">May we show approved work in our portfolio?</label><select id="portfolio" name="portfolio"><option value="no">No</option><option value="yes">Yes, with approval of each example</option></select></div><div className="field full"><label><input type="checkbox" name="consent" value="yes" required style={{width:"auto",marginRight:10}}/>I am authorized to provide this business information. *</label></div></div><button className="button" type="submit">Submit onboarding ↗</button></>}</form>}
