"use client";
import {useState} from "react";
import OpsActions from "./ops-actions";
type Row=Record<string,string|number|null>;
type Data={leads:Row[],clients:Row[],content:Row[],invoices:Row[],events:Row[]};
export default function Dashboard(){const [key,setKey]=useState("");const [data,setData]=useState<Data|null>(null);const [error,setError]=useState("");const [tab,setTab]=useState<keyof Data>("leads");
 async function load(){setError("");try{const r=await fetch("/api/admin",{headers:{"x-admin-key":key},cache:"no-store"});if(!r.ok)throw new Error(r.status===401?"Access key not accepted.":"Unable to load records.");setData(await r.json())}catch(e){setError(String(e))}}
 async function update(table:string,id:string,column:string,value:string){const r=await fetch("/api/admin",{method:"PATCH",headers:{"content-type":"application/json","x-admin-key":key},body:JSON.stringify({table,id,changes:{[column]:value}})});if(!r.ok){setError("Update failed; refresh before retrying.");return}await load()}
 return <div className="ops"><div className="ops-login"><label>Access key <input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)}/></label><button className="button" onClick={load}>Open records</button></div>{error&&<p role="alert" className="form-status error">{error}</p>}{data&&<><OpsActions data={data} accessKey={key} refresh={load} onError={setError}/><div className="ops-tabs">{(["leads","clients","content","invoices","events"] as const).map(x=><button key={x} onClick={()=>setTab(x)} aria-pressed={tab===x}>{x} ({data[x].length})</button>)}</div><div className="ops-table"><table><thead><tr>{Object.keys(data[tab][0]||{id:0}).map(x=><th key={x}>{x.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{data[tab].map(row=><tr key={String(row.id)}>{Object.entries(row).map(([column,v])=><td key={column}>{column==="status"&&tab!=="events"?<select value={String(v||"")} aria-label={tab+" status"} onChange={e=>update(tab,String(row.id),column,e.target.value)}>{[String(v||""),...new Set(tab==="leads"?["Lead","Qualified","Proposal","Contract Sent","Signed","Activation Paid","Onboarding","Production","Active","Paused","Cancellation Pending","Closed"]:tab==="content"?["Idea","Brief","Draft","Design/Edit","Internal QA","Client Review","Revision","Approved","Scheduled","Published","Measured"]:tab==="invoices"?["Planned","Due","Paid","Overdue","Void"]:["Pending signature","Onboarding","Production","Active","Paused","Cancellation Pending","Closed"])].map(x=><option key={x}>{x}</option>)}</select>:String(v??"")}</td>)}</tr>)}</tbody></table></div><p>Only the access key permits these records to load. Do not share it in a client document.</p></>}</div>}
