import { sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";
export const leads=sqliteTable("leads",{
 id:text("id").primaryKey(),company:text("company").notNull(),name:text("name").notNull(),email:text("email").notNull(),phone:text("phone"),packageInterest:text("package_interest"),contactPreference:text("contact_preference").notNull(),details:text("details").notNull(),source:text("source"),status:text("status").notNull().default("Lead"),createdAt:text("created_at").notNull(),lastContact:text("last_contact"),nextFollowUp:text("next_follow_up"),agreementStatus:text("agreement_status").default("Not sent"),activationStatus:text("activation_status").default("Not due"),onboardingStatus:text("onboarding_status").default("Not sent"),notes:text("notes")
});
export const clients=sqliteTable("clients",{
 id:text("id").primaryKey(),leadId:text("lead_id"),company:text("company").notNull(),contact:text("contact"),email:text("email"),package:text("package").notNull(),monthlyPrice:real("monthly_price").notNull(),activationFee:real("activation_fee").notNull(),startDate:text("start_date"),billingDate:text("billing_date"),status:text("status").notNull().default("Pending signature"),onboardingStatus:text("onboarding_status").notNull().default("Not sent"),accessStatus:text("access_status").notNull().default("Missing"),contentCycleStatus:text("content_cycle_status").default("Not started"),approvalStatus:text("approval_status").default("Not started"),metricoolStatus:text("metricool_status").default("Not connected"),reportingStatus:text("reporting_status").default("Not due"),notes:text("notes"),createdAt:text("created_at").notNull()
});
export const content=sqliteTable("content",{
 id:text("id").primaryKey(),clientId:text("client_id").notNull(),cycle:text("cycle").notNull(),number:integer("number").notNull(),pillar:text("pillar"),platform:text("platform"),format:text("format"),assetStatus:text("asset_status").default("Missing"),caption:text("caption"),creativeUrl:text("creative_url"),qaStatus:text("qa_status").default("Pending"),approvalStatus:text("approval_status").default("Pending"),revisionCount:integer("revision_count").default(0),stage:text("stage").notNull().default("Idea"),plannedDate:text("planned_date"),scheduledDate:text("scheduled_date"),publishedDate:text("published_date"),metricoolId:text("metricool_id"),performanceNotes:text("performance_notes"),updatedAt:text("updated_at").notNull()
});
export const invoices=sqliteTable("invoices",{
 id:text("id").primaryKey(),clientId:text("client_id").notNull(),cycle:text("cycle").notNull(),type:text("type").notNull(),baseAmount:real("base_amount").notNull(),credit:real("credit").notNull().default(0),amountDue:real("amount_due").notNull(),dueDate:text("due_date"),paidAt:text("paid_at"),status:text("status").notNull().default("Planned"),notes:text("notes")
});
export const events=sqliteTable("events",{id:text("id").primaryKey(),kind:text("kind").notNull(),entityId:text("entity_id"),at:text("at").notNull(),details:text("details")});
export const onboarding=sqliteTable("onboarding",{id:text("id").primaryKey(),clientId:text("client_id").notNull(),tokenHash:text("token_hash").notNull(),createdAt:text("created_at").notNull(),expiresAt:text("expires_at").notNull(),submittedAt:text("submitted_at"),responses:text("responses")});
