"use client";
import { useState } from "react";
import { useSearchParams } from "next/navigation";
export default function InquiryForm(){const params=useSearchParams();const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState(false);const [submitted,setSubmitted]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setStatus("");setError(false);const form=e.currentTarget;const data=Object.fromEntries(new FormData(form).entries());try{const r=await fetch("/api/inquiry",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error||"Please try again.");setStatus("Thank you. Your request was received. We’ll follow up using your preferred contact method.");setSubmitted(true);form.reset()}catch(ex){setStatus(ex instanceof Error?ex.message:"Unable to submit. Please email us directly.");setError(true)}finally{setBusy(false)}}
 return <form className="form-panel" onSubmit={submit} aria-label="New business inquiry"><h2 style={{fontSize:"2.5rem"}}>Tell us about your business</h2><p>Fields marked * are required. Please don’t include passwords or sensitive customer information.</p><div className="form-grid">
 <div className="field"><label htmlFor="company">Business name *</label><input id="company" name="company" required maxLength={120}/></div>
 <div className="field"><label htmlFor="name">Your name *</label><input id="name" name="name" autoComplete="name" required maxLength={120}/></div>
 <div className="field"><label htmlFor="email">Email *</label><input id="email" name="email" type="email" autoComplete="email" required maxLength={190}/></div>
 <div className="field"><label htmlFor="phone">Phone</label><input id="phone" name="phone" type="tel" autoComplete="tel" maxLength={40}/></div>
 <div className="field"><label htmlFor="package">Package interest</label><select id="package" name="package" defaultValue={params.get("package")||""}><option value="">Help me choose</option><option value="starter">Starter</option><option value="growth">Growth</option><option value="partner">Partner</option></select></div>
 <div className="field"><label htmlFor="contact">Best way to reach you *</label><select id="contact" name="contact" required><option value="email">Email</option><option value="phone">Phone</option></select></div>
 <div className="field full"><label htmlFor="details">What does your business do, and what help do you need? *</label><textarea id="details" name="details" required minLength={15} maxLength={2000}/></div>
 <div className="honeypot" aria-hidden="true"><label htmlFor="website">Leave this blank</label><input id="website" name="website" tabIndex={-1} autoComplete="off"/></div>
 <div className="field full"><label><input name="consent" type="checkbox" value="yes" required style={{width:"auto",marginRight:10}}/>I agree to be contacted about this request and have read the <a href="/privacy" target="_blank" rel="noopener noreferrer" style={{textDecoration:"underline"}}>Privacy Policy</a>. *</label></div></div>
 <p role="status" className={error?"form-status error":"form-status"}>{status}</p><button className="button" type="submit" disabled={busy||submitted}>{busy?"Sending…":submitted?"Request received":"Send my request ↗"}</button></form>}
